#include "bootstrap.h"

#ifdef ENABLE_MULTIPLAYER

#include "game_manifest.h"
#include "scenario_selection.h"
#include "mp_debug_log.h"
#include "player_registry.h"
#include "ownership.h"
#include "empire_sync.h"
#include "time_sync.h"
#include "command_bus.h"
#include "checksum.h"
#include "resync.h"
#include "worldgen.h"
#include "network/session.h"
#include "network/serialize.h"
#include "network/protocol.h"
#include "network/discovery_lan.h"
#include "scenario/empire.h"
#include "empire/city.h"
#include "game/file.h"
#include "game/state.h"
#include "core/log.h"
#include "core/string.h"
#include "window/city.h"
#include "graphics/window.h"

#include <string.h>
#include <stdlib.h>
#include <time.h>

static struct {
    mp_boot_state state;
    char scenario_name[MP_MANIFEST_SCENARIO_NAME_MAX];
} boot_data;

void mp_bootstrap_init(void)
{
    memset(&boot_data, 0, sizeof(boot_data));
    mp_game_manifest_init();
}

void mp_bootstrap_reset(void)
{
    boot_data.state = MP_BOOT_IDLE;
    memset(boot_data.scenario_name, 0, sizeof(boot_data.scenario_name));
    mp_game_manifest_clear();
    scenario_empire_set_multiplayer_mode(0);
}

mp_boot_state mp_bootstrap_get_state(void)
{
    return boot_data.state;
}

void mp_bootstrap_set_scenario(const char *scenario_name)
{
    if (!scenario_name || !scenario_name[0]) {
        return;
    }
    strncpy(boot_data.scenario_name, scenario_name,
            MP_MANIFEST_SCENARIO_NAME_MAX - 1);
    boot_data.scenario_name[MP_MANIFEST_SCENARIO_NAME_MAX - 1] = '\0';
    boot_data.state = MP_BOOT_SCENARIO_SELECTED;

    MP_LOG_INFO("BOOT", "Scenario selected: '%s'", boot_data.scenario_name);
}

const char *mp_bootstrap_get_scenario_name(void)
{
    return boot_data.scenario_name;
}

static uint32_t generate_session_seed(void)
{
    srand((unsigned int)time(NULL));
    return (uint32_t)rand() ^ ((uint32_t)rand() << 16);
}

static int load_scenario_locally(const char *scenario_name)
{
    /* Convert ASCII scenario name to uint8_t for Augustus API */
    uint8_t name_buf[MP_MANIFEST_SCENARIO_NAME_MAX];
    string_copy(string_from_ascii(scenario_name), name_buf,
                MP_MANIFEST_SCENARIO_NAME_MAX);

    MP_LOG_INFO("BOOT", "Loading scenario locally: '%s'", scenario_name);

    if (!game_file_start_scenario_by_name(name_buf)) {
        MP_LOG_ERROR("BOOT", "Failed to load scenario: '%s'", scenario_name);
        return 0;
    }

    MP_LOG_INFO("BOOT", "Scenario loaded successfully: '%s'", scenario_name);
    return 1;
}

void mp_bootstrap_bind_loaded_scenario(void)
{
    MP_LOG_INFO("BOOT", "Binding multiplayer subsystems to loaded scenario");

    /* 1. Enable multiplayer mode flag */
    scenario_empire_set_multiplayer_mode(1);

    /* 2. Initialize subsystems (but NOT player_registry — preserve lobby roster) */
    mp_ownership_init();
    mp_empire_sync_init();
    mp_time_sync_init();
    mp_command_bus_init();
    mp_checksum_init();
    mp_resync_init();

    /* 3. Assign empire cities to players using the spawn table.
     *    The spawn table was generated by the host and replicated to clients.
     *    Each spawn entry maps a slot_id to an empire_city_id. */
    const mp_spawn_table *table = mp_worldgen_get_spawn_table();
    uint8_t local_id = net_session_get_local_player_id();

    for (int i = 0; i < table->spawn_count; i++) {
        const mp_spawn_entry *spawn = &table->spawns[i];
        if (!spawn->valid) {
            continue;
        }

        /* Find the player who owns this slot */
        mp_player *player = mp_player_registry_get_by_slot(spawn->slot_id);
        if (!player || !player->active) {
            MP_LOG_WARN("BOOT", "No player for slot %d (city %d) — skipping",
                        (int)spawn->slot_id, spawn->empire_city_id);
            continue;
        }

        int city_id = spawn->empire_city_id;

        if (player->player_id == local_id) {
            /* This is our city */
            empire_city_set_owner(city_id, CITY_OWNER_LOCAL, player->player_id);
            mp_ownership_set_city(city_id, MP_OWNER_LOCAL_PLAYER, player->player_id);
        } else {
            /* Remote player's city */
            empire_city_set_owner(city_id, CITY_OWNER_REMOTE, player->player_id);
            mp_ownership_set_city(city_id, MP_OWNER_REMOTE_PLAYER, player->player_id);
        }

        mp_player_registry_set_city(player->player_id, city_id);
        mp_player_registry_set_assigned_city(player->player_id, city_id);

        /* Register in empire sync for trade view replication */
        if (net_session_is_host()) {
            mp_empire_sync_register_player_city(city_id, player->player_id,
                                                 spawn->empire_object_id);
        }

        MP_LOG_INFO("BOOT", "City %d assigned to player %d (slot %d, %s)",
                    city_id, (int)player->player_id, (int)spawn->slot_id,
                    player->player_id == local_id ? "local" : "remote");
    }

    MP_LOG_INFO("BOOT", "Multiplayer subsystems bound to scenario");
}

static void broadcast_spawn_table(void)
{
    uint8_t spawn_buf[2048];
    uint32_t spawn_size = 0;
    mp_worldgen_serialize(spawn_buf, &spawn_size);

    /* Send as HOST_EVENT with NET_EVENT_SPAWN_TABLE_UPDATED */
    uint8_t event_buf[2048 + 16];
    net_serializer es;
    net_serializer_init(&es, event_buf, sizeof(event_buf));
    net_write_u16(&es, NET_EVENT_SPAWN_TABLE_UPDATED);
    net_write_u32(&es, 0); /* event tick — game hasn't started yet */
    net_write_u32(&es, spawn_size);
    net_write_raw(&es, spawn_buf, spawn_size);

    net_session_broadcast(NET_MSG_HOST_EVENT, event_buf,
                          (uint32_t)net_serializer_position(&es));

    MP_LOG_INFO("BOOT", "Spawn table broadcast: %u bytes, %d spawns",
                spawn_size, (int)mp_worldgen_get_spawn_table()->spawn_count);
}

int mp_bootstrap_host_start_game(void)
{
    if (!net_session_is_host()) {
        MP_LOG_ERROR("BOOT", "Only host can start the game");
        return 0;
    }

    if (boot_data.scenario_name[0] == '\0') {
        MP_LOG_ERROR("BOOT", "No scenario selected");
        return 0;
    }

    boot_data.state = MP_BOOT_PREPARING;

    /* 1. Build the manifest with real scenario hash */
    uint32_t seed = generate_session_seed();
    int player_count = net_session_get_peer_count() + 1; /* +1 for host */

    uint32_t scenario_hash = 0;
    if (!mp_scenario_compute_file_hash(boot_data.scenario_name, &scenario_hash)) {
        MP_LOG_WARN("BOOT", "Could not compute scenario hash — continuing without");
    }

    mp_game_manifest_set(MP_GAME_MODE_SCENARIO, boot_data.scenario_name,
                         scenario_hash, scenario_hash, 0, seed, NET_MAX_PLAYERS);
    mp_game_manifest_set_player_count((uint8_t)player_count);

    /* Store seed in spawn table for worldgen */
    mp_worldgen_get_spawn_table_mutable()->session_seed = seed;

    /* 2. Send GAME_PREPARE (manifest) to all peers */
    {
        uint8_t manifest_buf[256];
        uint32_t manifest_size = 0;
        mp_game_manifest_serialize(manifest_buf, &manifest_size);

        /* We need to broadcast to peers in JOINED/READY state, not just IN_GAME.
         * Use send_to_peer directly since broadcast only sends to IN_GAME peers. */
        for (int i = 0; i < NET_MAX_PEERS; i++) {
            const net_peer *peer = net_session_get_peer(i);
            if (peer && peer->active) {
                net_session_send_to_peer(i, NET_MSG_GAME_PREPARE,
                                         manifest_buf, manifest_size);
            }
        }

        MP_LOG_INFO("BOOT", "GAME_PREPARE sent to %d peers", player_count - 1);
    }

    /* 3. Load scenario locally */
    if (!load_scenario_locally(boot_data.scenario_name)) {
        MP_LOG_ERROR("BOOT", "Host failed to load scenario — aborting game start");
        boot_data.state = MP_BOOT_SCENARIO_SELECTED;
        return 0;
    }

    /* 3b. Validate scenario has enough eligible cities for player count */
    if (!mp_scenario_validate_for_multiplayer(player_count)) {
        MP_LOG_ERROR("BOOT", "Scenario '%s' does not support %d players — aborting",
                     boot_data.scenario_name, player_count);
        boot_data.state = MP_BOOT_SCENARIO_SELECTED;
        return 0;
    }

    /* 4. Generate worldgen spawns */
    mp_worldgen_init();
    if (!mp_worldgen_generate_player_spawns(seed, player_count, 1)) {
        MP_LOG_ERROR("BOOT", "Worldgen failed: no valid spawn configuration");
        boot_data.state = MP_BOOT_SCENARIO_SELECTED;
        return 0;
    }
    mp_worldgen_lock();

    /* 5. Bind multiplayer subsystems to the loaded scenario */
    mp_bootstrap_bind_loaded_scenario();

    /* 6. Apply spawns to empire (create city ownership records) */
    mp_worldgen_apply_spawns();

    /* 7. Transition session to in-game state (sets peers to IN_GAME) */
    net_session_start_game();

    /* 8. Broadcast spawn table to clients (must be AFTER start_game
     *    because broadcast only sends to PEER_STATE_IN_GAME peers) */
    broadcast_spawn_table();

    /* 9. Send GAME_START_FINAL to all peers (they are now IN_GAME) */
    {
        uint8_t start_buf[8];
        net_serializer ss;
        net_serializer_init(&ss, start_buf, sizeof(start_buf));
        net_write_u32(&ss, 0); /* start tick */
        net_write_u8(&ss, 2);  /* normal speed */
        net_session_broadcast(NET_MSG_GAME_START_FINAL, start_buf,
                              (uint32_t)net_serializer_position(&ss));
    }

    /* 10. Stop LAN discovery announcing (game is in progress) */
    net_discovery_stop_announcing();

    /* 11. Transition to WINDOW_CITY */
    boot_data.state = MP_BOOT_IN_GAME;
    window_city_show();

    MP_LOG_INFO("BOOT", "=== Game started successfully ===");
    MP_LOG_INFO("BOOT", "Scenario: '%s', Players: %d, Seed: %u",
                boot_data.scenario_name, player_count, seed);

    return 1;
}

int mp_bootstrap_client_prepare(const uint8_t *payload, uint32_t size)
{
    MP_LOG_INFO("BOOT", "GAME_PREPARE received from host (%u bytes)", size);

    /* 1. Deserialize manifest */
    if (!mp_game_manifest_deserialize(payload, size)) {
        MP_LOG_ERROR("BOOT", "Failed to deserialize game manifest");
        return 0;
    }

    const mp_game_manifest *manifest = mp_game_manifest_get();

    /* 2. Store session seed for worldgen */
    mp_worldgen_get_spawn_table_mutable()->session_seed = manifest->session_seed;

    /* 3. Copy scenario name to boot data */
    strncpy(boot_data.scenario_name, manifest->scenario_name,
            MP_MANIFEST_SCENARIO_NAME_MAX - 1);
    boot_data.state = MP_BOOT_PREPARING;

    /* 4. Load the scenario locally */
    if (!load_scenario_locally(manifest->scenario_name)) {
        MP_LOG_ERROR("BOOT", "Client failed to load scenario '%s'",
                     manifest->scenario_name);
        return 0;
    }

    /* 4b. Validate scenario hash matches host's manifest */
    if (manifest->scenario_hash != 0) {
        uint32_t local_hash = 0;
        if (mp_scenario_compute_file_hash(manifest->scenario_name, &local_hash)) {
            if (!mp_scenario_hashes_match(local_hash, manifest->scenario_hash)) {
                MP_LOG_ERROR("BOOT", "Scenario hash mismatch — client has different "
                             "version of '%s'", manifest->scenario_name);
                return 0;
            }
        } else {
            MP_LOG_WARN("BOOT", "Could not compute local hash for validation");
        }
    }

    /* 5. Initialize worldgen (client doesn't generate, waits for spawn table) */
    mp_worldgen_init();

    boot_data.state = MP_BOOT_LOADED;

    MP_LOG_INFO("BOOT", "Client prepared: scenario '%s' loaded, waiting for spawn table",
                manifest->scenario_name);
    return 1;
}

int mp_bootstrap_client_enter_game(void)
{
    MP_LOG_INFO("BOOT", "GAME_START_FINAL received — entering game");

    /* The spawn table should have arrived via HOST_EVENT before this message.
     * Bind subsystems now that we have both scenario and spawn data. */
    const mp_spawn_table *table = mp_worldgen_get_spawn_table();
    if (table->spawn_count == 0) {
        MP_LOG_WARN("BOOT", "Entering game with empty spawn table — "
                    "city assignment may be incomplete");
    }

    /* Lock the spawn table on client side too */
    mp_worldgen_lock();

    /* Bind multiplayer subsystems */
    mp_bootstrap_bind_loaded_scenario();

    /* Apply spawns (client-side ownership records) */
    mp_worldgen_apply_spawns();

    /* Stop LAN discovery listening */
    net_discovery_stop_listening();

    /* Transition to gameplay */
    boot_data.state = MP_BOOT_IN_GAME;
    window_city_show();

    MP_LOG_INFO("BOOT", "=== Client entered game ===");
    return 1;
}

#endif /* ENABLE_MULTIPLAYER */
