#ifndef SCENARIO_EVENT_CITY_PROPERTY_H
#define SCENARIO_EVENT_CITY_PROPERTY_H

typedef enum {
    CITY_PROPERTY_NONE,
    CITY_PROPERTY_DIFFICULTY,
    CITY_PROPERTY_MONEY,
    CITY_PROPERTY_POPULATION,
    CITY_PROPERTY_SAVINGS,
    CITY_PROPERTY_YEAR_FINANCE_BALANCE,
    CITY_PROPERTY_RESOURCE_STOCK,
    CITY_PROPERTY_STATS_FAVOR,
    CITY_PROPERTY_STATS_PROSPERITY,
    CITY_PROPERTY_STATS_CULTURE,
    CITY_PROPERTY_STATS_PEACE,
    CITY_PROPERTY_STATS_CITY_HEALTH,
    CITY_PROPERTY_POPS_UNEMPLOYMENT,
    CITY_PROPERTY_ROME_WAGES,
    CITY_PROPERTY_CITY_WAGES,
    CITY_PROPERTY_BUILDING_COUNT_ACTIVE,
    CITY_PROPERTY_BUILDING_COUNT_ANY,
    CITY_PROPERTY_TROOPS_COUNT_PLAYER,
    CITY_PROPERTY_TROOPS_COUNT_ENEMY,
    CITY_PROPERTY_TERRAIN_COUNT_TILES,
    CITY_PROPERTY_MAX,
} city_property_t;

#endif // SCENARIO_EVENT_CITY_PROPERTY_H