#ifndef SCENARIO_EVENT_CITY_PROPERTY_H
#define SCENARIO_EVENT_CITY_PROPERTY_H

typedef enum {
    CITY_PROPERTY_NONE,
    CITY_PROPERTY_DIFFICULTY,
    CITY_PROPERTY_MONEY,
    CITY_PROPERTY_POPULATION,
    CITY_PROPERTY_SAVINGS,
    CITY_PROPERTY_YEAR_FINANCE_BALANCE,
    CITY_PROPERTY_RESOURCE_STOCK, //complex
    // stats
    CITY_PROPERTY_STATS_FAVOR,
    CITY_PROPERTY_STATS_PROSPERITY,
    CITY_PROPERTY_STATS_CULTURE,
    CITY_PROPERTY_STATS_PEACE,
    CITY_PROPERTY_STATS_CITY_HEALTH,
    // service coverage
    CITY_PROPERTY_SERVICE_COVERAGE,//complex
    // Population
    CITY_PROPERTY_POPS_UNEMPLOYMENT,//complex
    CITY_PROPERTY_POPS_HOUSING_TYPE,//complex
    CITY_PROPERTY_POPS_BY_AGE,//complex
    CITY_PROPERTY_ROME_WAGES,
    CITY_PROPERTY_CITY_WAGES,
    // buildings
    CITY_PROPERTY_BUILDING_COUNT_ACTIVE,//complex
    CITY_PROPERTY_BUILDING_COUNT_ANY,//complex
    //troops
    CITY_PROPERTY_TROOPS_COUNT_PLAYER,//complex
    CITY_PROPERTY_TROOPS_COUNT_ENEMY,//complex
    //terrain
    CITY_PROPERTY_TERRAIN_COUNT_TILES,//complex
    CITY_PROPERTY_MAX,
} city_property_t;

int process_parameter(city_property_t type);

#endif // SCENARIO_EVENT_CITY_PROPERTY_H