#ifndef MAP_ROUTING_DATA_H
#define MAP_ROUTING_DATA_H

#include "map/grid.h"

enum { // Includes movement cost
    TERRAIN_ACCESS_CITIZEN_ROAD = 100,
    TERRAIN_ACCESS_CITIZEN_HIGHWAY = 50,
    TERRAIN_ACCESS_CITIZEN_PASSABLE = 100,
    TERRAIN_ACCESS_CITIZEN_EMPTY = 200,
    TERRAIN_ACCESS_CITIZEN_BLOCKED = 200, // Might be destroyable
    TERRAIN_ACCESS_CITIZEN_AQUEDUCT = 200,
    TERRAIN_ACCESS_CITIZEN_RESERVOIR_CONNECTOR = 200,

    TERRAIN_ACCESS_NONCITIZEN_PASSABLE = 100,
    TERRAIN_ACCESS_NONCITIZEN_BUILDING = 200,
    TERRAIN_ACCESS_NONCITIZEN_CLEARABLE = 200,
    TERRAIN_ACCESS_NONCITIZEN_GATEHOUSE = 200,
    TERRAIN_ACCESS_NONCITIZEN_FORT = 200,
    TERRAIN_ACCESS_NONCITIZEN_BLOCKED = 200,

    TERRAIN_ACCESS_WATER = 100,
    TERRAIN_ACCESS_WATER_LOW_BRIDGE = 100, // Small boats can be added!
    TERRAIN_ACCESS_WATER_BLOCKED = 100,
    TERRAIN_ACCESS_WATER_EDGE = 200,

    TERRAIN_ACCESS_WALL_PASSABLE = 100,
    TERRAIN_ACCESS_WALL_BLOCKED = 200,
};

extern grid_i8 terrain_access_citizen;
extern grid_i8 terrain_access_noncitizen;
extern grid_i8 terrain_access_water;
extern grid_i8 terrain_access_walls;

#endif // MAP_ROUTING_DATA_H
