name: macOS Release Build

on:
  workflow_dispatch:   # allows you to run this on demand from the Actions tab

jobs:
  build-macos:
    runs-on: macos-latest
    name: Build & Release macOS
    env:
      SDL_VERSION: 2.32.8
      SDL_MIXER_VERSION: 2.8.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install cmake sdl2 sdl2_mixer

      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel
        
      - name: Package macOS binary
        run: |
          mkdir -p package
          # Copy the actual binary out of the .app bundle
          cp build/augustus.app/Contents/MacOS/augustus package/augustus
          # Copy the .app itself (so testers can double-click it like a normal Mac app)
          cp -R build/augustus.app package/
          # Copy SDL2 dylibs (optional — only if you want standalone without Homebrew)
          cp $(brew --prefix sdl2)/lib/libSDL2-2.0.0.dylib package/ || true
          cp $(brew --prefix sdl2_mixer)/lib/libSDL2_mixer-2.0.0.dylib package/ || true
          cd package
          zip -r ../augustus-macos.zip .


      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: macos-build-${{ github.run_number }}
          name: "macOS Build ${{ github.run_number }}"
          draft: true
          files: augustus-macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
