// DO NOT EDIT. This file is generated by CMake.
// Run CMake configure step to update it.
#include "game/system.h"

#define AUGUSTUS_VERSION "4.0.0"
#define AUGUSTUS_VERSION_SUFFIX ".1295-d4dafc30e"

const char *system_version(void)
{
    return AUGUSTUS_VERSION AUGUSTUS_VERSION_SUFFIX;
}
